name: First Workflow
on: workflow_dispatch 
jobs:
 first-job:
  runs-on: windows-latest
  steps:
   - name: Print branch name 
     run: echo "runnig on ${GITHUB_REF##*/}"
   - name: Print greeting
     run: echo "Hellow world!"
   - name: Printing final message
     run: echo "Done - Process completed..."
