name: First Workflow
on: workflow_dispatch 
 #branches: [main]
jobs:
 first-job:
  runs-on: ubuntu-latest
  steps:
   -name: Print greeting
    run: echo "Hellow world!"
   -name: Printing final message
    run: echo "Done - Process completed..."
